import { LoanStatus } from '../../../models/loans/Loan';
import { BorrowerStatus } from '../../../models/loans/Borrower';
import { loansInitialState, LoansState } from '../loans.reducers';

export const CURRENT_STATE_updateLoanStatus: LoansState = {
  loans: [
    {
      id: '1',
      loanAmount: 60000,
      interestRate: 4.8,
      startDate: '2023-03-10',
      endDate: '2025-03-10',
      outstandingBalance: 58000,
      status: LoanStatus.Current,
      borrower: {
        id: '1',
        fullName: 'Sharkiesha',
        accountNumber: 'ACC',
        status: BorrowerStatus.Active,
        creditScore: 200,
        loanCount: 2,
        createdAt: new Date(),
        lastUpdated: new Date(),
        address: 'string',
        notes: 'string',
      },
    },
    {
      id: '2',
      loanAmount: 60000,
      interestRate: 4.8,
      startDate: '2023-03-10',
      endDate: '2025-03-10',
      outstandingBalance: 58000,
      status: LoanStatus.Current,
      borrower: {
        id: '1',
        fullName: 'Sharkiesha',
        accountNumber: 'ACC',
        status: BorrowerStatus.Active,
        creditScore: 200,
        loanCount: 2,
        createdAt: new Date(),
        lastUpdated: new Date(),
        address: 'string',
        notes: 'string',
      },
    },
  ],
  loading: false,
  displayableLoans: [
    {
      id: '1',
      loanAmount: 60000,
      interestRate: 4.8,
      startDate: '2023-03-10',
      endDate: '2025-03-10',
      outstandingBalance: 58000,
      status: LoanStatus.Current,
      borrower: {
        id: '1',
        fullName: 'Sharkiesha',
        accountNumber: 'ACC',
        status: BorrowerStatus.Active,
        creditScore: 200,
        loanCount: 2,
        createdAt: new Date(),
        lastUpdated: new Date(),
        address: 'string',
        notes: 'string',
      },
    },
    {
      id: '2',
      loanAmount: 60000,
      interestRate: 4.8,
      startDate: '2023-03-10',
      endDate: '2025-03-10',
      outstandingBalance: 58000,
      status: LoanStatus.Current,
      borrower: {
        id: '1',
        fullName: 'Sharkiesha',
        accountNumber: 'ACC',
        status: BorrowerStatus.Active,
        creditScore: 200,
        loanCount: 2,
        createdAt: new Date(),
        lastUpdated: new Date(),
        address: 'string',
        notes: 'string',
      },
    },
  ],
  selectedLoan: {
    id: '1',
    loanAmount: 60000,
    interestRate: 4.8,
    startDate: '2023-03-10',
    endDate: '2025-03-10',
    outstandingBalance: 58000,
    status: LoanStatus.Current,
    borrower: {
      id: '1',
      fullName: 'Sharkiesha',
      accountNumber: 'ACC',
      status: BorrowerStatus.Active,
      creditScore: 200,
      loanCount: 2,
      createdAt: new Date(),
      lastUpdated: new Date(),
      address: 'string',
      notes: 'string',
    },
  },
  isUpdatingLoans: false,
};

export const CURRENT_STATE_filterLoans: LoansState = {
  ...loansInitialState,
  loans: [
    {
      id: '1',
      loanAmount: 60000,
      interestRate: 4.8,
      startDate: '2023-03-10',
      endDate: '2025-03-10',
      outstandingBalance: 58000,
      status: LoanStatus.WrittenOff,
      borrower: {
        id: '1',
        fullName: 'Sharkiesha',
        accountNumber: 'ACC',
        status: BorrowerStatus.Active,
        creditScore: 200,
        loanCount: 2,
        createdAt: new Date(),
        lastUpdated: new Date(),
        address: 'string',
        notes: 'string',
      },
    },
    {
      id: '2',
      loanAmount: 60000,
      interestRate: 4.8,
      startDate: '2023-03-10',
      endDate: '2025-03-10',
      outstandingBalance: 58000,
      status: LoanStatus.Current,
      borrower: {
        id: '1',
        fullName: 'Sharkiesha',
        accountNumber: 'ACC',
        status: BorrowerStatus.Active,
        creditScore: 200,
        loanCount: 2,
        createdAt: new Date(),
        lastUpdated: new Date(),
        address: 'string',
        notes: 'string',
      },
    },
    {
      id: '3',
      loanAmount: 60000,
      interestRate: 4.8,
      startDate: '2023-03-10',
      endDate: '2025-03-10',
      outstandingBalance: 58000,
      status: LoanStatus.Current,
      borrower: {
        id: '1',
        fullName: 'Sharkiesha',
        accountNumber: 'ACC',
        status: BorrowerStatus.Active,
        creditScore: 200,
        loanCount: 2,
        createdAt: new Date(),
        lastUpdated: new Date(),
        address: 'string',
        notes: 'string',
      },
    },
  ],
};
